/*REMOVE ALL COMMENTS BEFORE RUNNING*/

DROP TABLE Booking CASCADE CONSTRAINT;
DROP TABLE NonTenant_Booking CASCADE CONSTRAINT;
DROP TABLE TenantApartment CASCADE CONSTRAINT;
DROP TABLE Facility CASCADE CONSTRAINT;
DROP TABLE Apartment CASCADE CONSTRAINT;
DROP TABLE Building CASCADE CONSTRAINT;
DROP TABLE PersonEmail CASCADE CONSTRAINT;
DROP TABLE PersonPhoneNo CASCADE CONSTRAINT;
DROP TABLE Person CASCADE CONSTRAINT;

